### PR TITLE
Add Mneme example

### PR DESCRIPTION
**Pull request by zachallaun**
Adds an example of using [Mneme](https://github.com/zachallaun/mneme) with ExUnit.

Note that running the example will modify the file 🙂

### CODE REVIEW

**Comment by wojtekmach** [comment]
> Note that running the example will modify the file

Yeah, that's a no go as eventually I'd inadvertently commit the updated file which defeats the purpose. Could you write the test file to a temp directory and then run it? A bit similar idea as in https://github.com/wojtekmach/mix_install_examples/blob/main/ex_doc.exs.

Awesome library, btw!

**Comment by zachallaun** [comment]
Understood!

There’s a semi-private dry-run option for demo purposes that we can enable with `Application.put_env(:mneme, :dry_run, true)`. In retrospect I should have added that to start :). On my phone now but will update the PR later today.

**Comment by zachallaun** [comment]
Made a [few small changes](https://github.com/wojtekmach/mix_install_examples/compare/f7b56aad917d5094e2732057c2d65e029db9c18a..d4b39cb20bae4208ad5d2d465d667b6c43477a1d):

- `:dry_run` to skip writing to file
- `ExUnit.start(seed: 0)` to run tests in consistent order
- `@mneme default_pattern: :last` for `auto_assert_raise` example to display assertion with message by default:

    ```elixir
    auto_assert_raise(ArgumentError, "expected a string, got '1, 2, 3'", fn ->
      parse_ints('1, 2, 3')
    end)
    ```

**Comment by wojtekmach** [comment]
Awesome, thank you!

**Comment by wojtekmach** [comment]
Wait, did we have interactive [y]es / [n]o / [s]kip input all along? I think I either miss it or didn't realise it. I removed dry run setting because I don't think I need it, I'll just skip things, and this way people wouldn't be surprised if they run the file locally. Sorry for confusion!

**Comment by zachallaun** [comment]
@wojtekmach Yep, they were there! And no worries 🙂 Thanks for merging!

**Pull request merged**
